### ISSUE TITLE
Remove features for branch to give to new lab

### ISSUE THREAD

**Issue by willbarkoff** [CoursesPlus/CoursesPlus#12]
The new branch I created is to give to the new lab. We will remove all features except those going into courses 2016.

**Comment by thatoddmailbox** [comment]
I'm not sure how necessary this is; components.js is already pretty separated already.

**Comment by thatoddmailbox** [comment]
Closing because Courses integration didn't work out and I don't know how required it is because the components are already separated.

@nywillb If you think this is necessary, reopen it.
