### ISSUE TITLE
Extensions are blocked on student laptops

### ISSUE THREAD

**Issue by thatoddmailbox** [CoursesPlus/CoursesPlus#13]
See title.

**Comment by willbarkoff** [comment]
Ohhhhhhhhhh Nooooooooooooooooooooooooooooooo

**Comment by willbarkoff** [comment]
^Initial Reaction^
@thatoddmailbox  How did you find this out? I have an idea but it would take forever to make:

We make a jar web browser just for going to Courses with Courses**Plus** enabled. This should be used in worst case situations

**Comment by medensqui** [comment]
Yeah we should schedule a lab with NLTL (New Lab) at THE VERY BEGINNING of the school year. So that we can clarify and try to find workarounds or get special exceptions

**Comment by willbarkoff** [comment]
@medensqui We have to find a lab time that works for all of us. It should be easier because you will be in high school so you will have more free periods.

**Comment by thatoddmailbox** [comment]
@nywillb @medensqui I've checked Firefox and Safari. Both have addons/extensions blocked. Java .jar files still run. Most application-running loopholes seem blocked. Also, private browsing/incognito modes seem to be turned off.

@medensqui "workarounds or get special exceptions" - unless they preinstall CoursesPlus on every computer at the beginning of the year, this isn't possible with how they block it. If they _did_ preinstall it, we would not be able to easily update it.

The way they block installation of extensions is to lock down the folders where extensions are installed so only admins can edit them.

**Comment by thatoddmailbox** [comment]
@medensqui @nywillb Check your CoursesPlus emails. (if you forgot the site, [here's a link](https://internal.coursesplus.tk))

**Comment by thatoddmailbox** [comment]
@nywillb "How did you find this out?" - High School orientation was today, and we all got our laptops (assuming parents submitted signed forms ahead of time).

**Comment by thatoddmailbox** [comment]
@medensqui @nywillb I have an idea for a workaround that won't annoy the New Lab.

Chrome has a feature called "external extensions". You write a file with an extension ID in a special folder, and Chrome will install the extension on next startup. [See here for details.](https://developer.chrome.com/extensions/external_extensions)

We could wrote a Java installer program that would do the following:
1. Tell user to close all open Chrome windows.
2. Create an external extensions file telling Chrome to install CoursesPlus.
3. Unlock the extension folder.
4. Open Chrome.
5. Allow user to approve install (idk what popups external extensions triggers, will have to check)
6. Close Chrome.
7. Lock the extension folder.
8. Do all this while covering the screen with a blank window so the user can't interfere. This would install CoursesPlus, allow updates, and do it all in a New Lab-friendly way (extension folder is still locked, so no proxy extensions) This should be an idea we propose to them at the meeting.

I am on mobile now, but I'll try to see if I can make a prototype later today.

Also, it's important to note that developer mode/unpacked extensions work fine.

**Comment by medensqui** [comment]
@thatoddmailbox @nywillb I think that works. Just in case they don't approve of it, we could still just do the developer mode (which is user unfriendly) but that works regardless.

**Comment by thatoddmailbox** [comment]
@medensqui @nywillb The problem with developer mode is updating would require you to have a Java program hanging out in the background and that would copy files when needed. Also, [read this post by the Chrome team](http://blog.chromium.org/2015/05/continuing-to-protect-chrome-users-from.html). Essentially, it says "all users with developer mode extensions will get a scary warning message when they open Chrome". They previously did this on Windows, and are now planning to do this on Mac.

The warning message looks like this: 
![warning message](http://i.stack.imgur.com/861MU.png)

It requires you to click "Cancel" every time you open Chrome, and cannot be disabled. If you press "Disable", CoursesPlus is removed. :cry:

**Comment by medensqui** [comment]
So Studer when is NLTL doing the whitelist? And how should we keep it up to date?

**Comment by medensqui** [comment]
oops

**Comment by thatoddmailbox** [comment]
@medensqui When they feel like it? I did share it with them..... I can poke someone at house tomorrow.

We could email them when someone asks us for something? Or maybe tell people to email them directly? Or maybe a monthly update...

**Comment by medensqui** [comment]
@nywillb @thatoddmailbox Uh closing...
