### ISSUE TITLE
Firefox WebExtensions version

### ISSUE THREAD

**Issue by thatoddmailbox** [CoursesPlus/CoursesPlus#18]
I've made a branch, `firefox-webextensions`, to try making a version of CoursesPlus compatible with the new [WebExtensions system](https://wiki.mozilla.org/Browser_Extensions) in Firefox.

Unfortunately, it has to be in a separate branch because it requires making some changes to manifest.json that breaks compatibility with Chrome.

**Comment by willbarkoff** [comment]
This is not much of an issue, so I am closing it.
