### ISSUE TITLE
Small Question

### ISSUE THREAD

**Issue by c20ms1** [CoursesPlus/CoursesPlus#19]
Why go straight to opera, rather than firefox?
_Thanks_

**Comment by thatoddmailbox** [comment]
@c20ms1 The new versions of Opera are based off of Chrome and can load Chrome extensions&mdash;we didn't have to do any work to port it, we could just submit it to the Opera addon store. There is a Firefox version in the works, but we are waiting for the new Firefox WebExtensions system to be stable (it is similar to programming extensions for Chrome, so it will be easier for us to use)
