### ISSUE TITLE
Navbar has scrollbars on small screens

### ISSUE THREAD

**Issue by thatoddmailbox** [CoursesPlus/CoursesPlus#5]
![screen shot 2015-06-03 at 1 31 42 pm](https://cloud.githubusercontent.com/assets/1904587/7966883/e2238cba-09f4-11e5-85ae-0fa7ca8af793.png)

**Comment by thatoddmailbox** [comment]
This is more visible on a Windows computer, but I don't have access to one right now.

**Comment by thatoddmailbox** [comment]
@nywillb This should be in Courses 2016 Integration because if New Lab adds the new navbar, this bug will appear and cause eternal sadness for anyone on a Windows machine or a Mac with the right settings.

**Comment by willbarkoff** [comment]
Ok
