### ISSUE TITLE
Milestones/version plans

### ISSUE THREAD

**Issue by thatoddmailbox** [CoursesPlus/CoursesPlus#8]
3.3.0 is scheduled right now for June 27th, 2015. Yet 3.3.5 (maybe @nywillb  meant 3.**2**.5?) is set for June 8th, 2015.

June 27th is way after Arch Day. Why is an update scheduled for when Courses is offline and the userbase count will significantly decrease (due to computers being wiped) so there will be very little people to install the update?

Wouldn't it be smarter to just bundle all the features into 4.0?

**Comment by willbarkoff** [comment]
Yes, I meant 3.2.5

**Comment by willbarkoff** [comment]
Oh. Good point.

**Comment by thatoddmailbox** [comment]
@nywillb OK, I fixed that for you.
